// export const markers = [
//   {
//     id: 1,
//     position: [51.505, -0.09],
//     title: "London, UK",
//     image: "https://upload.wikimedia.org/wikipedia/commons/c/cd/London_Montage_L.jpg",
//     description: "Famous for Big Ben and the River Thames."
//   },
//   {
//     id: 2,
//     position: [48.8566, 2.3522],
//     title: "Paris, France",
//     image: "https://upload.wikimedia.org/wikipedia/commons/a/a8/Tour_Eiffel_Wikimedia_Commons.jpg",
//     description: "The city of lights and the Eiffel Tower."
//   },
//   {
//     id: 3,
//     position: [40.7128, -74.0060],
//     title: "New York, USA",
//     image: "https://upload.wikimedia.org/wikipedia/commons/a/a1/Lower_Manhattan_from_Jersey_City_November_2014_panorama_3.jpg",
//     description: "The city that never sleeps."
//   }
// ];
export const markers =[
  { id: 1, position: [24.00, 54.00], title: "United Arab Emirates", image: "https://source.unsplash.com/300x200/?dubai", description: "Remote work visa valid for 1 year, proof of employment and health insurance required." },
  { id: 2, position: [41.00, 20.00], title: "Albania", image: "https://source.unsplash.com/300x200/?albania", description: "Digital nomad permit up to 1 year, renewable." },
  { id: 3, position: [18.25, -63.17], title: "Anguilla", image: "https://source.unsplash.com/300x200/?anguilla", description: "12-month nomad visa; income documentation needed." },
  { id: 4, position: [17.05, -61.80], title: "Antigua and Barbuda", image: "https://source.unsplash.com/300x200/?antigua+barbuda", description: "Nomad Digital Residence valid for 2 years with proof of remote income." },
  { id: 5, position: [-34.00, -64.00], title: "Argentina", image: "https://source.unsplash.com/300x200/?argentina", description: "Temporary residence for remote workers up to 1 year." },
  { id: 6, position: [40.00, 45.00], title: "Armenia", image: "https://source.unsplash.com/300x200/?armenia", description: "Long stays allowed via tourist route; no formal nomad visa yet." },
  { id: 7, position: [12.50, -69.97], title: "Aruba", image: "https://source.unsplash.com/300x200/?aruba", description: "Special remote work program for up to 3 months." },
  { id: 8, position: [-25.00, 133.00], title: "Australia", image: "https://source.unsplash.com/300x200/?australia", description: "No dedicated nomad visa yet, tourist/working holiday routes often used." },
  { id: 9, position: [24.25, -76.00], title: "Bahamas", image: "https://source.unsplash.com/300x200/?bahamas", description: "BEATS digital nomad visa: 1 year, extendable up to 3." },
  { id: 10, position: [-10.00, -55.00], title: "Brazil", image: "https://source.unsplash.com/300x200/?brazil", description: "VITEM XIV nomad visa: 1 year (renewable), requires US$1,500/month or US$18,000 savings." },
  { id: 11, position: [13.17, -59.50], title: "Barbados", image: "https://source.unsplash.com/300x200/?barbados", description: "Welcome Stamp: 12 months stay with ≥ US$50,000/year proof of income." },
  { id: 12, position: [17.25, -88.75], title: "Belize", image: "https://source.unsplash.com/300x200/?belize", description: "Work Where You Vacation: 6 months valid with ≥ US$75,000/year income." },
  { id: 13, position: [32.30, -64.75], title: "Bermuda", image: "https://source.unsplash.com/300x200/?bermuda", description: "Work From Bermuda Certificate: 1 year, documentation and fee required." },
  { id: 14, position: [16.00, -24.00], title: "Cape Verde", image: "https://source.unsplash.com/300x200/?cape+verde", description: "Digital nomad visa offers up to 6 months stay." },
  { id: 15, position: [19.50, -80.50], title: "Cayman Islands", image: "https://source.unsplash.com/300x200/?cayman+islands", description: "1-Year Visa for Global Citizens: proof of employment and health insurance required." },
  { id: 16, position: [4.00, -72.00], title: "Colombia", image: "https://source.unsplash.com/300x200/?colombia", description: "Digital Nomad Visa: up to 2 years with ≥ US$1,150/month income requirement." },
  { id: 17, position: [10.00, -84.00], title: "Costa Rica", image: "https://source.unsplash.com/300x200/?costa+rica", description: "Digital Nomad Visa: 1 year (renewable), ≥ US$3,000/month or US$5,000 for families." },
  { id: 18, position: [45.17, 15.50], title: "Croatia", image: "https://source.unsplash.com/300x200/?croatia", description: "Nomad Visa: up to 1 year; tax exemption on remote income." },
  { id: 19, position: [12.17, -68.97], title: "Curacao", image: "https://source.unsplash.com/300x200/?curacao", description: "Remote job permit available, details vary by employer." },
  { id: 20, position: [35.00, 33.00], title: "Cyprus", image: "https://source.unsplash.com/300x200/?cyprus", description: "Nomad Visa offers up to 1 year stay, flexible income documentation." },
  { id: 21, position: [49.75, 15.50], title: "Czech Republic", image: "https://source.unsplash.com/300x200/?czech+republic", description: "5-Year visa for freelancers and remote workers: Czech Blue Card route often used." },
  { id: 22, position: [15.42, -61.33], title: "Dominica", image: "https://source.unsplash.com/300x200/?dominica", description: "Work in Nature Visa: up to 18 months, ≥ US$50,000/year and fee required." },
  { id: 23, position: [-2.00, -77.50], title: "Ecuador", image: "https://source.unsplash.com/300x200/?ecuador", description: "Rentista Visa: up to 2 years, requires US$1,380/month or US$15,500/year in savings." },
  { id: 24, position: [13.83, -88.92], title: "El Salvador", image: "https://source.unsplash.com/300x200/?el+salvador", description: "Special tourist visa available; formal nomad visa in progress." },
  { id: 25, position: [27.00, 30.00], title: "Egypt", image: "https://source.unsplash.com/300x200/?egypt", description: "Long-term remote work permit under development." },
  { id: 26, position: [59.00, 26.00], title: "Estonia", image: "https://source.unsplash.com/300x200/?estonia", description: "Digital Nomad Visa: up to 1 year; ≥ €3,504/month and remote contract needed." },
  { id: 27, position: [46.00, 2.00], title: "France", image: "https://source.unsplash.com/300x200/?france", description: "Self-employed visa or long-stay visa option used by nomads." },
  { id: 28, position: [42.00, 43.50], title: "Georgia", image: "https://source.unsplash.com/300x200/?georgia+country", description: "Remotely from Georgia program: 6 months, no taxes for certain durations." },
  { id: 29, position: [51.00, 9.00], title: "Germany", image: "https://source.unsplash.com/300x200/?germany", description: "Freelance visa (Freiberufler) used; not exclusive nomad visa." },
  { id: 30, position: [39.00, 22.00], title: "Greece", image: "https://source.unsplash.com/300x200/?greece", description: "Digital Nomad Visa: 1 year (extendable), ≥ €3,740/month and health insurance." },
  { id: 31, position: [47.00, 20.00], title: "Hungary", image: "https://source.unsplash.com/300x200/?hungary", description: "White Card: 1 year, renewable; ≥ €2,000–3,000/month required." },
  { id: 32, position: [65.00, -18.00], title: "Iceland", image: "https://source.unsplash.com/300x200/?iceland", description: "Remote Work Visa: up to 180 days; around US$7,700/month income proof." },
  { id: 33, position: [53.00, -8.00], title: "Ireland", image: "https://source.unsplash.com/300x200/?ireland", description: "Stamp 0 visa or business permission used for remote workers." },
  { id: 34, position: [42.83, 12.83], title: "Italy", image: "https://source.unsplash.com/300x200/?italy", description: "Digital Nomad Visa introduced in some regions; others use freelance visas." },
  { id: 35, position: [35.83, 14.50], title: "Malta", image: "https://source.unsplash.com/300x200/?malta", description: "Nomad Residence Permit: 1 year renewable, ≥ €34,615/year." },
  { id: 36, position: [35.00, 33.00], title: "Cyprus Duplicate", image: "https://source.unsplash.com/300x200/?cyprus", description: "Duplicate entry placeholder." },
  { id: 37, position: [52.50, 5.75], title: "Netherlands", image: "https://source.unsplash.com/300x200/?netherlands", description: "Self-employed residence permit may be used; no dedicated nomad visa yet." },
  { id: 38, position: [55.00, 37.00], title: "Russia", image: "https://source.unsplash.com/300x200/?russia", description: "No digital nomad visa; using tourist/business visas instead." },
  { id: 39, position: [41.50, 22.00], title: "North Macedonia", image: "https://source.unsplash.com/300x200/?north+macedonia", description: "Nomad visa pilot under consideration." },
  { id: 40, position: [44.00, 21.00], title: "Serbia", image: "https://source.unsplash.com/300x200/?serbia", description: "Digital Nomad Visa: up to 1 year; proof of income and background check required." },
  { id: 41, position: [46.00, 25.00], title: "Romania", image: "https://source.unsplash.com/300x200/?romania", description: "Remote worker visa launched; residence possible for up to 1 year." },
  { id: 42, position: [-41.00, 174.00], title: "New Zealand", image: "https://source.unsplash.com/300x200/?new+zealand", description: "Job visa programs used; no specific nomad visa yet." },
  { id: 43, position: [62.00, 10.00], title: "Norway", image: "https://source.unsplash.com/300x200/?norway", description: "Tourist visa only; remote work visa in discussion." },
  { id: 44, position: [9.00, -80.00], title: "Panama", image: "https://source.unsplash.com/300x200/?panama", description: "Short Stay Visa: 9 months, ≥ US$36,000/year and application fees." },
  { id: 45, position: [-10.00, -76.00], title: "Peru", image: "https://source.unsplash.com/300x200/?peru", description: "No specific nomad visa; tourist visas extended on case-by-case basis." },
  { id: 46, position: [13.00, 122.00], title: "Philippines", image: "https://source.unsplash.com/300x200/?philippines", description: "Special Resident Retiree’s Visa (SRRV) often used by long-stay nomads." },
  { id: 47, position: [39.00, 35.00], title: "Türkiye", image: "https://source.unsplash.com/300x200/?turkey", description: "Digital Nomad Visa available for remote workers with income proof." },
  { id: 48, position: [15.00, 100.00], title: "Thailand", image: "https://source.unsplash.com/300x200/?thailand", description: "Smart Visa category may apply; true nomad visa in development." },
  { id: 49, position: [23.50, 121.00], title: "Taiwan", image: "https://source.unsplash.com/300x200/?taiwan", description: "Nomad pilot program offering short-term remote work stays." },
  { id: 50, position: [7.00, 81.00], title: "Sri Lanka", image: "https://source.unsplash.com/300x200/?sri+lanka", description: "Tourist visa can be extended; no formal nomad visa currently." },
  { id: 51, position: [36.00, 138.00], title: "Japan", image: "https://source.unsplash.com/300x200/?japan", description: "No formal nomad visa; remote work rule through long-term business/working visas." },
  { id: 52, position: [37.00, 127.50], title: "South Korea", image: "https://source.unsplash.com/300x200/?south+korea", description: "D‑8 Remote Work Visa pilot underway for select professionals." },
  { id: 53, position: [16.17, 107.83], title: "Vietnam", image: "https://source.unsplash.com/300x200/?vietnam", description: "Digital nomad visa pilot being tested— conditions vary." },
  { id: 54, position: [16.75, -62.20], title: "Montserrat", image: "https://source.unsplash.com/300x200/?montserrat", description: "Remote Workers Stamp: 12 months, ≥ US$70,000/year income." },
  { id: 55, position: [13.92, -60.97], title: "Saint Lucia", image: "https://source.unsplash.com/300x200/?saint+lucia", description: "Live It visa: 1 year stay with proof of income and fees." }
]

